disabled_rules: 
  - identifier_name
  - trailing_whitespace
  - todo
  - redundant_string_enum_value

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - build

line_length: 200