disabled_rules: 
  - identifier_name
  - trailing_whitespace
  - todo
  - redundant_string_enum_value
  - valid_ibinspectable
  - for_where
  - trailing_comma
  - function_body_length
  - type_body_length
  - file_length

included: 
  - Cactus

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - build
  - vendor
  - Cactus/SwiftyGif

line_length: 200