# .circleci/config.yml
version: 2.1
executors: 
  cactus-ios: 
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.3.0"
    environment:
      FL_OUTPUT_DIR: output

commands: 
  install-ruby: 
    steps: 
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  install: 
    steps: 
      - install-ruby
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: bundle exec pod install --verbose

jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
          destination: swiftlint
      - store_test_results:
          path: result.xml
          destination: swiftlint
  build-and-test:
    executor: cactus-ios    
    shell: /bin/bash --login -o pipefail
    steps:
      - install
      - run:
          name: Build and run tests
          command: bundle exec fastlane test
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Cactus Prod
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  testflight-upload: 
    executor: cactus-ios
    steps: 
      - checkout
      - install
      - run:
          name: Deploy to TestFlight
          command: bundle exec fastlane beta                
      - store_artifacts:
          path: output
  testflight-finalize-release: 
    executor: cactus-ios
    steps: 
      - install-ruby
      - run:
          name: Finalize Release & upload symbols
          command: bundle exec fastlane finalize_release
      - store_artifacts:
          path: output

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
      - testflight_approval:
          type: approval
          name: &testflight_approval_name "TestFlight Approval"
          requires: 
            - build-and-test
      - testflight-upload:
          name: &testflight_name "Deploy to Testflight"
          requires: 
            - *testflight_approval_name
      - finalize-release-approval: 
          type: approval
          name: &finalize-release-approval "Finalze Release"
          requires: 
            - *testflight_name
      - testflight-finalize-release:
          name: "Upload Symbols to Sentry & Create Release"
          requires: 
            - *finalize-release-approval



