# .circleci/config.yml
version: 2
executors: 
  cactus-ios: 
    working_directory: ~/project
    macos:
      xcode: "10.3.0"
    environment:
      FL_OUTPUT_DIR: output
jobs:
  build-and-test:
    executor: cactus-ios
    # macos:
    #   xcode: "10.3.0"
    # environment:
    #   FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Cactus Prod
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  testflight: 
    executor: cactus-ios
    steps: 
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose

      - run:
          name: Deploy to TestFlight
          command: bundle exec fastlane beta          
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - testflight_approval
        type: approval
        name: &testflight_approval_name "Upload to TestFlight"
        requires: 
            - build-and-test

