# .circleci/config.yml
version: 2.1
executors: 
  cactus-ios: 
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.3.0"
    environment:
      FL_OUTPUT_DIR: fl_output
aliases: 
  - &match-ssh-fingerprint "4b:a2:6f:21:f5:6a:c2:26:05:b4:10:29:01:17:7c:51"
  - &cactus-ios-read-write-fingerprint "ca:4b:99:13:a3:ba:7c:8e:9b:2a:f5:2a:e9:95:9e:a8"
commands:
  restore-pods-cache: 
    steps: 
      - restore_cache:
          name: "Restore Pods Cache"
          key: 1-pods-{{ checksum "Podfile.lock" }}
  restore-caches:
    steps:
      - restore-pods-cache
      - restore_cache:
          name: "Restore Ruby Cache"
          key: 2-gems-{{ checksum "Gemfile.lock" }}      
  install-ruby: 
    steps: 
      - restore_cache:
          name: "Restore Ruby Cache"
          key: 2-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          name: "Save Ruby Cache"
          key: 2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - vendor
            - .bundle
  install-pods:
    steps: 
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - restore-pods-cache
      - run:
          name: "Install CocoaPods"
          command: bundle exec pod install --verbose
      - save_cache:
          name: "Save Pods Cache"
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
  install: 
    steps:       
      - install-ruby
      - install-pods    
jobs:  
  key-test: 
    executor: cactus-ios
    steps: 
      - checkout
  build-and-test:
    executor: cactus-ios    
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - install-ruby
      - run: 
          name: Install Swiftlint via homebrew
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
      - run: 
          name: SwiftLint lane
          command: bundle exec fastlane lint
      - install-pods      
      - run:
          name: Build and run tests
          command: bundle exec fastlane test
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Cactus Prod
      - run:
          name: "Print files in directory"
          command: ls -la 
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_test_results:
          path: fl_output/scan
      - store_artifacts:
          path: fl_output            
  testflight-upload: 
    executor: cactus-ios
    steps: 
      - checkout      
      - install-ruby
      - restore-pods-cache
      - add_ssh_keys:
          name: "Add Fastlane Match SSH Key"
          fingerprints:
            - *match-ssh-fingerprint
            - *cactus-ios-read-write-fingerprint
      - run:
          name: Deploy to TestFlight
          command: bundle exec fastlane beta                
      - store_artifacts:
          path: fl_output
  testflight-finalize-release: 
    executor: cactus-ios
    steps: 
      - install-ruby
      - add_ssh_keys:
          fingerprints:
            - *match-ssh-fingerprint
            - *cactus-ios-read-write-fingerprint
      - run:
          name: Finalize Release & upload symbols
          command: bundle exec fastlane finalize_release
      - store_artifacts:
          path: fl_output
  version-bump:
    executor: cactus-ios
    steps: 
      - checkout
      - install-ruby
      - add_ssh_keys:
          fingerprints:            
            - *cactus-ios-read-write-fingerprint
      - run:
          name: "Fastlane Version Bump"
          command: bundle exec fastlane version_bump
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
      - testflight_approval:
          type: approval
          name: &testflight_approval_name "TestFlight Approval"
          requires: 
            - build-and-test
      - version-bump:
          name: &version_bump_name "Bump Build Version"
          requires: 
            - *testflight_approval_name
      - testflight-upload:
          name: &testflight_name "Deploy to Testflight"
          requires: 
            - *testflight_approval_name      
            - *version_bump_name
      - finalize-release-approval: 
          type: approval
          name: &finalize-release-approval "Finalze Release"
          requires: 
            - *testflight_name
      - testflight-finalize-release:
          name: "Upload Symbols to Sentry & Create Release"
          requires: 
            - *finalize-release-approval



