# .circleci/config.yml
version: 2.1
orbs:
  slack: circleci/slack@3.2.0 #https://github.com/CircleCI-Public/slack-orb
executors: 
  cactus-ios: 
    working_directory: /Users/distiller/project
    macos:
      xcode: "11.0.0"
    environment:
      FL_OUTPUT_DIR: fl_output
  cactus-web:
    working_directory: ~/project  
    docker:
      - image: circleci/node:8.15.0-browsers
jobs:  
  create-job:
      executor: cactus-ios
      steps: 
          - checkout
          - run: 
              name: "Create a new directory and files"
              command: |
                mkdir neil-test
                echo 'My Files One!' >> neil-test/one.txt
                echo 'My Files Two!' >> neil-test/two.txt
                echo 'My Files Three!' >> neil-test/three.txt
          - run: 
              name: "List files"
              command: |
                echo Root Project Files
                ls -la
                echo Neil-Test files
                ls -la neil-test
          - persist_to_workspace: 
              root: '.'
              paths: 
                  - neil-test
  restore-job:
      executor: cactus-ios
      steps: 
          - checkout
          - run: 
              name: "List files before restore"
              command: |
                echo Root Project Files
                ls -la
                echo **** Neil-Test files ****
                ls -la neil-test || echo None
          - attach_workspace:
              at: '.'
          - run: 
              name: "List files after restore"
              command: |
                echo Root Project Files
                ls -la
                echo ****  Neil-Test files ****
                ls -la neil-test || echo None

                echo **** restored-test **** 
                ls -la restored-test
workflows:
  version: 2.1
  test-pipeline:
    jobs:
      - create-job
      - restore-job:
          requires: 
            - create-job

   


